browser: "chrome"
projectEnvironments:
  preProd:
    BaseURL: "https://sc-backend-dev-4.homelane.com"
    SynapseUrl: "https://synapse-preprod.homelane.com"
    NucleusUrl: "https://nucleus-api-preprod.homelane.com"
    RoasterBaseUrl: "https://dc-rosters-preprod.homelane.com"
  prod:
    BaseURL: "https://sc-backend-production.homelane.com"
    SynapseUrl: "https://nucleus-synapse-prod.homelane.com"
    RoasterBaseUrl: "https://dc-orderwise.homelane.com"
    ScProUrl: "https://spacecraft-pro.homelane.com"